#image: node:latest
#stages:
# - build
# - test
# - deploy
#test:
#  stage: test
#  script:
#    - npm test
test:
  script: 
    - echo "Hello World"
    - mkdir build
    - touch build/computer.txt
    - echo "Mainboard" > build/computer.txt
    - cat build/computer.txt
